---
version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1026
      - PGID=1000
      - TZ=US/Eastern
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=hansoky #optional
      - PASS=watson10 #optional
      - WHITELIST=iplist #optional
      - PEERPORT=peerport #optional
      - HOST_WHITELIST=dnsname list #optional
    volumes:
      - /volume1/docker/transmission/data:/config
      - /volume1/docker/transmission/downloads:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped